/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ForgetPassword;

import com.Loginpage.Login;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author 91898
 */
public class ChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form ChangePassword
     */
    
    private String email;
    
    
    public void sendEmail(String email){
        this.email = email;
    }
    public ChangePassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Password = new javax.swing.JFormattedTextField();
        CPassword = new javax.swing.JFormattedTextField();
        registrationbtn1 = new com.Registration.Registrationbtn();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(442, 354));
        setMinimumSize(new java.awt.Dimension(442, 354));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Poor Richard", 0, 28)); // NOI18N
        jLabel3.setText("Change Password ");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 10, 210, 35);

        jLabel4.setFont(new java.awt.Font("Poor Richard", 0, 28)); // NOI18N
        jLabel4.setText("Confirm New Password");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 190, 260, 35);

        jLabel5.setFont(new java.awt.Font("Poor Richard", 0, 28)); // NOI18N
        jLabel5.setText("New Password");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 80, 210, 35);

        try {
            Password.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(Password);
        Password.setBounds(20, 120, 270, 30);

        try {
            CPassword.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(CPassword);
        CPassword.setBounds(20, 230, 270, 30);

        registrationbtn1.setBackground(new java.awt.Color(255, 104, 0));
        registrationbtn1.setBorder(null);
        registrationbtn1.setForeground(new java.awt.Color(255, 255, 255));
        registrationbtn1.setText("Submit");
        registrationbtn1.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        registrationbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(registrationbtn1);
        registrationbtn1.setBounds(180, 280, 90, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-7, -3, 410, 330);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void registrationbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationbtn1ActionPerformed
        // TODO add your handling code here:
        Forget f = new Forget();
        if(email.isEmpty()){
         System.out.print("Empty");
        }
        else{       System.out.print(email);
        }
String newPassword = Password.getText();
        if(Password.getText().isEmpty()||CPassword.getText().isEmpty()){
             JOptionPane.showMessageDialog(null, "Password cannot be null");
        }
        else{
            
            if(Password.getText().equals(CPassword.getText())) {          
              try{
             Class.forName("com.mysql.cj.jdbc.Driver");
     Connection c = DriverManager.getConnection("jdbc:mysql:///projectmanager", "root", "Him@nshu2004");

                   PreparedStatement updatePs = c.prepareStatement("update login set Pass = ? where Email = ?");
            updatePs.setString(1, newPassword);
            updatePs.setString(2, email);
           int rowsAffected = updatePs.executeUpdate();

        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(null, "Password Updated Successfully");
            Login l = new Login();
            l.setVisible(true);
            System.out.print("hemant ");
        } else {
            JOptionPane.showMessageDialog(null, "No matching record found for the given email.");
        }
              }
        catch(Exception e){
            e.printStackTrace();
        }
        }
            else{
                 JOptionPane.showMessageDialog(null,"Password And Confirm Password Should be same !!");      
            }
        }
    
    }//GEN-LAST:event_registrationbtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField CPassword;
    private javax.swing.JFormattedTextField Password;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private com.Registration.Registrationbtn registrationbtn1;
    // End of variables declaration//GEN-END:variables
}
