/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Game;

/**
 *
 * @author 91898
 */
public class GamesPanel extends javax.swing.JFrame {

    /**
     * Creates new form GamesPanel
     */
    public GamesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        snakeGamePanel1 = new com.Game.SnakeGamePanel();
        tetrisGamePanel1 = new com.Game.TetrisGamePanel();
        Home = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(472, 368));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setLayout(null);

        snakeGamePanel1.setBackground(new java.awt.Color(204, 204, 204));
        snakeGamePanel1.setBorder(null);
        snakeGamePanel1.setText("snakeGamePanel1");
        snakeGamePanel1.setBottomleft(500);
        snakeGamePanel1.setBottomright(500);
        snakeGamePanel1.setContentAreaFilled(false);
        snakeGamePanel1.setFocusPainted(false);
        snakeGamePanel1.setTopleft(500);
        snakeGamePanel1.setTopright(500);
        snakeGamePanel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snakeGamePanel1ActionPerformed(evt);
            }
        });
        jPanel1.add(snakeGamePanel1);
        snakeGamePanel1.setBounds(30, 70, 82, 80);

        tetrisGamePanel1.setBackground(new java.awt.Color(102, 255, 102));
        tetrisGamePanel1.setBorder(null);
        tetrisGamePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Icons/Tt.png"))); // NOI18N
        tetrisGamePanel1.setBottomleft(500);
        tetrisGamePanel1.setBottomright(500);
        tetrisGamePanel1.setContentAreaFilled(false);
        tetrisGamePanel1.setFocusPainted(false);
        tetrisGamePanel1.setTopleft(500);
        tetrisGamePanel1.setTopright(500);
        tetrisGamePanel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tetrisGamePanel1ActionPerformed(evt);
            }
        });
        jPanel1.add(tetrisGamePanel1);
        tetrisGamePanel1.setBounds(150, 70, 85, 80);

        Home.setFont(new java.awt.Font("Candara", 0, 34)); // NOI18N
        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Icons/Gameslogo.png"))); // NOI18N
        Home.setText("Games");
        jPanel1.add(Home);
        Home.setBounds(150, 10, 170, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 480, 370);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void snakeGamePanel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snakeGamePanel1ActionPerformed
  Main m = new Main();
  m.setVisible(true);
    }//GEN-LAST:event_snakeGamePanel1ActionPerformed

    private void tetrisGamePanel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tetrisGamePanel1ActionPerformed
       Tetris t = new Tetris();
       t.setVisible(true);
    }//GEN-LAST:event_tetrisGamePanel1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GamesPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GamesPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GamesPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamesPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GamesPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Home;
    private javax.swing.JPanel jPanel1;
    private com.Game.SnakeGamePanel snakeGamePanel1;
    private com.Game.TetrisGamePanel tetrisGamePanel1;
    // End of variables declaration//GEN-END:variables
}
